compressionLevel: mixed

nodeLinker: node-modules

packageExtensions:
  "astro@*":
    dependencies:
      zod: "^3.25.76"

npmScopes:
  abinnovision:
    npmAlwaysAuth: false
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"
